<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="28063" started-at="2020-06-29T11:22:03 IST" finished-at="2020-06-29T11:22:31 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="28063" started-at="2020-06-29T11:22:03 IST" finished-at="2020-06-29T11:22:31 IST">
      <class name="com.training.sanity.tests.AdminRecoverPasswordTests">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.AdminRecoverPasswordTests@614ddd49]" name="setUpBeforeClass" is-config="true" duration-ms="9" started-at="2020-06-29T11:22:03 IST" finished-at="2020-06-29T11:22:03 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.AdminRecoverPasswordTests@614ddd49]" name="setUp" is-config="true" duration-ms="19528" started-at="2020-06-29T11:22:03 IST" finished-at="2020-06-29T11:22:22 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="recoveryPwdTest()[pri:0, instance:com.training.sanity.tests.AdminRecoverPasswordTests@614ddd49]" name="recoveryPwdTest" duration-ms="6755" started-at="2020-06-29T11:22:22 IST" finished-at="2020-06-29T11:22:29 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [A confirmation link has been sent to your email address. Message should get displayed & confirmation mail should be sent to registered mail id] but found [The email could not be sent.
Possible reason: your host may have disabled the mail() function.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [A confirmation link has been sent to your email address. Message should get displayed & confirmation mail should be sent to registered mail id] but found [The email could not be sent.
Possible reason: your host may have disabled the mail() function.]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.training.sanity.tests.AdminRecoverPasswordTests.recoveryPwdTest(AdminRecoverPasswordTests.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- recoveryPwdTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.AdminRecoverPasswordTests@614ddd49]" name="tearDown" is-config="true" duration-ms="1720" started-at="2020-06-29T11:22:29 IST" finished-at="2020-06-29T11:22:31 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.AdminRecoverPasswordTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
